- id: rust-format
  name: rust format
  description: Format Rust files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: rust-check
  name: rust check
  description: Check Rust package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
